site_name: My Note Book
site_url: https://tristanedu.github.io/note-book/
repo_name: TristanEDU/note-book
repo_url: https://github.com/TristanEDU/note-book

docs_dir: docs
use_directory_urls: false

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Optional extras - Uncomment if you want to re-enable custom CSS or social links
#extra_css:
#  - stylesheets/extra.css
#  - stylesheets/links.css

#extra:
#  social:
#    - icon: fontawesome/brands/github-alt
#      link: https://github.com/TristanEDU
#    - icon: fontawesome/solid/rss
#      link: https://lyz-code.github.io/blue-book/newsletter/0_newsletter_index


repo_name: TristanEDU/note-book
repo_url: https://github.com/TristanEDU/note-book
