name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install MkDocs and Material theme
        run: pip install mkdocs-material

      - name: Force deploy with MkDocs
        run: mkdocs gh-deploy --force --verbose
